### ISSUE TITLE
Parser Error with special characters

### ISSUE THREAD

**Issue by skualoerp** [proudmonkey/AutoWrapper#3] opened 2019-10-03 06:54 UTC
Hi,

If the response contains special characters like é ú ñ, etc, returns a bad JSON response. 

Bad Response example:
SyntaxError: JSON.parse: end of data after property value in object at line 1 column 61 of the JSON data
{"statusCode":200,"isError":false,"result":"Jaime Sepúlveda"

**Comment by proudmonkey** [comment] 2019-10-03 16:01
@skualoerp 

I just tested the wrapper with special characters as you mentioned and it seems to work just fine. Here my sample GET method:

`
[HttpGet]
public async Task<string> Get()
{
    await Task.Delay(1000);
    return "Jaime Sepúlveda é ú ñ";
}
`
And here's the response:

`{
    "message": "Request successful.",
    "isError": false,
    "result": "Jaime Sepúlveda é ú ñ"
}`

You should check your JSON payload and ensure it's valid.

**Comment by proudmonkey** [comment] 2019-10-04 05:56
Closing as I can't reproduce the issue. If you can provide a steps to repro, feel free to reopen this.

Thank you.

**Closed by proudmonkey** 2019-10-04 05:56 UTC
