### ISSUE TITLE
IsApiOnly not working for Blazor app

### ISSUE THREAD

**Issue by dbowser** [proudmonkey/AutoWrapper#9] opened 2019-10-23 22:20 UTC
Hello,

This is breaking our Blazor WebAssembly app.
It now comes up with the message to set the flag. I did that but it didn't help.

I modified Startup.cs of my server with:
             app.UseApiResponseAndExceptionWrapper(new AutoWrapperOptions { IsApiOnly = false });

Is there something else I should do?

BTW, when you mention the flag in the readme it would be very helpful to provide context such as what method in what file needs to be modified.

I hope we can get an answer quickly so we can continue using this.

**Comment by proudmonkey** [comment] 2019-10-24 00:46
Thank you for the feedback. 

I wonder how did you add `AutoWrapper` in your app. Blazor Webassembly (a.k.a Client-side Blazor) targets `netstandard2.x` and `AutoWrapper` doesn't support that.

To use `AutoWrapper`, you should implement your API's in a separate ASP.NET Core project and then call your API from your Blazor Client app. This way, you don't need to set the `IsApiOnly` in the middleware.

**Comment by dbowser** [comment] 2019-10-24 12:58
AutoWrapper.Core 2.0.1 is only installed on my Server project which is 'netcoreapp3.0'
However, this project does serve the WebAssembly files, css, index.html, etc to load the client.
It was working recently but after an update I now do not get my app page but just the warning page from AutoWrapper. Adding IsApiOnly = false like it recommends did nothing to address the problem as far as I can tell.

**Comment by dbowser** [comment] 2019-10-24 13:15
Have you tested this with Blazor WebAssembly like just the template project? 
Could you?

**Comment by proudmonkey** [comment] 2019-10-24 18:51
I was using the Blazor App (`blazorserver`) default template in VS 2019 .NET Core 3.x and it doesn't contain the old Server and Shared projects. I also tried using the Blazor WebAssembly (`blazorwasm`) project using the following template:

`Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview1.19508.20`

and that was targeting to netstandard2.x. 

If you could give me the steps to repro and what specific projects templates you used, that would be helpful. 

For the time being, please revert back to the version where it was working.

**Comment by proudmonkey** [comment] 2019-10-25 01:37
@dbowser  I think I figured what you are experiencing. I've created a new Blazor Wasm with ASPNET Core hosted. Added AutoWrapper 2.0.1 annd configured the wrapper. I run the app in IISExpress and it seems to work just fine, but if you run the app using Kestrel, that where the issue comes up. 

I'll look into this and get back to you. Thanks for the update.

**Comment by proudmonkey** [comment] 2019-10-25 02:32
@dbowser - I've verified the code and seems like the logic is correct. The issue is seems like related to browser cache behavior in running in Kestrel. Try to do a hard refresh in your browser (CTRL + F5) and see if you are still seeing the warning message. Note that the app is working fine when running in IISExpress.

**Comment by dbowser** [comment] 2019-10-25 13:39
Great! That did it! 
Thank you!

**Comment by proudmonkey** [comment] 2019-10-25 16:30
No problem! I'm happy that you also use this in your project. If you don't mind giving a star to show support :)

I'm closing this issue now.

Thanks,
Vince

**Closed by proudmonkey** 2019-10-25 16:30 UTC
