### ISSUE TITLE
Int gets automatically converted to string

### ISSUE THREAD

**Issue by oktay89** [proudmonkey/AutoWrapper#32] opened 2020-02-18 16:00 UTC
I am using AutoWrapper 3.0. This is the Api Function i call:

```csharp
[HttpGet("loadInt")]
public int LoadInt(int schiffnr)
{
       return 13;
 }
```

This is the configuration I made:

```csharp
 app.UseApiResponseAndExceptionWrapper<WrapperPM>(new AutoWrapperOptions { UseCamelCaseNamingStrategy = false });`
```
This is my custom response class:

```csharp
public class WrapperPM
{
        [AutoWrapperPropertyMap(Prop.Result)]
        public object Data { get; set; }

        [AutoWrapperPropertyMap(Prop.Message)]
        public string ErrorMessage { get; set; }

        [AutoWrapperPropertyMap(Prop.ResponseException)]
        public CustomError Error { get; set; }

        [AutoWrapperPropertyMap(Prop.IsError)]
        public bool hasError { get; set; }
}
```

I expect the Data attribute to be int, but it is string.

```json
{"$id":"1052","Data": "111","ErrorMessage":null,"Error":null,"hasError":false}
```

**Comment by proudmonkey** [comment] 2020-02-18 19:23
Thank for the feedback!

Seems like this is an expected behavior for the current implementation because the return types  are automatically serialized to JSON string for sanity check. 

I have added a fix for this should be available in the next release.  

For the time being, you can use the `ApiResponse` object as the return type to return the actual type:
```
[HttpGet("loadInt")]
public ApiResponse LoadInt(int i)
{
            return new ApiResponse(13);
}
```

**Comment by oktay89** [comment] 2020-02-21 10:17
Will this bugfix fix also the double "double quotation marks" on a string function?
For Example:
`        [HttpGet("testString")]
        public string TestString()
        {
            return "test";
        }`

Returns:
`{"Message":"Request successful.","hasError":false,"Data":"\"test\""}`

**Comment by proudmonkey** [comment] 2020-02-22 01:53
@oktay89 regular strings should work not unless if you serialize it to `JSON`. For example:

```csharp
        [HttpGet("testString")] 
        public string TestString() { return JsonConvert.SerializeObject ("test"); }
```

Check your project/controller configuration and verify if you have this format specifier:

```csharp
[Produces("application/json")]
```

**Comment by proudmonkey** [comment] 2020-02-22 02:36
I will include a fix for this as well so that the body will be validated to avoid re enconding the JSON value.

**Comment by proudmonkey** [comment] 2020-02-26 02:10
Just released a new version that comes with a fix for this issue. You can find it here: [AutoWrapper Now Supports Problem Details For Your ASP.NET Core APIs](http://vmsdurano.com/autowrapper-now-supports-problemdetails/http://vmsdurano.com/autowrapper-now-supports-problemdetails/)

Thank you so much for all your suggestions on improving this middleware! :)

**Closed by proudmonkey** 2020-02-26 02:10 UTC
Labels: bug
