### ISSUE TITLE
Latest version drastically reduce the response time

### ISSUE THREAD

**Issue by tauqeer79** [proudmonkey/AutoWrapper#38] opened 2020-03-18 04:43 UTC
The response time is too slow when I upgraded the to the latest version. You can consider it like 10 times slower. I have reverted to version 2.1 and performance is normal.
I implemented in the .net Core 3.1.

**Comment by proudmonkey** [comment] 2020-03-18 05:29
Can you please provide a benchmark for your comparison? How many records are you testing? GET? POST?

**Comment by proudmonkey** [comment] 2020-04-07 14:41
Closing this issue as I can replicate it. Feel free to reopen it and provide a benchmark for us to analyze the cause. Thank you.

**Closed by proudmonkey** 2020-04-07 14:41 UTC
